"""initial route optimizer schema

Revision ID: 20260905_0001
Revises: 
Create Date: 2026-09-05 21:42:21.651357
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260905_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "route_optimizer"'))
    op.create_table('optimization_runs',
    sa.Column('route_request_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('trip_version', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('input_snapshot_uri', sa.String(length=500), nullable=True),
    sa.Column('solver_name', sa.String(length=100), nullable=False),
    sa.Column('solver_version', sa.String(length=100), nullable=False),
    sa.Column('config_version', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.String(length=50), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('vehicle_capacity_weight', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('vehicle_capacity_volume', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_sanitized', sa.Text(), nullable=True),
    sa.Column('fallback_reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'INFEASIBLE', 'CANCELED')", name=op.f('ck_optimization_runs_optimization_run_status')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_optimization_runs_optimization_execution_time_order')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_optimization_runs_optimization_latency')),
    sa.CheckConstraint('random_seed >= 0', name=op.f('ck_optimization_runs_optimization_seed_nonnegative')),
    sa.CheckConstraint('stop_count > 0', name=op.f('ck_optimization_runs_optimization_stop_count_positive')),
    sa.CheckConstraint('trip_version IS NULL OR trip_version > 0', name=op.f('ck_optimization_runs_optimization_trip_version')),
    sa.CheckConstraint('vehicle_capacity_volume > 0', name=op.f('ck_optimization_runs_vehicle_volume_positive')),
    sa.CheckConstraint('vehicle_capacity_weight > 0', name=op.f('ck_optimization_runs_vehicle_weight_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_runs')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_optimization_runs_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'route_request_id', name='ux_optimization_run_route_request'),
    schema='route_optimizer'
    )
    op.create_index('ix_optimization_run_correlation', 'optimization_runs', ['tenant_id', 'correlation_id'], unique=False, schema='route_optimizer')
    op.create_index('ix_optimization_run_status_age', 'optimization_runs', ['tenant_id', 'status', 'created_at'], unique=False, schema='route_optimizer', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING') AND deleted_at IS NULL"))
    op.create_index('ix_optimization_run_trip', 'optimization_runs', ['tenant_id', 'trip_id', 'trip_version'], unique=False, schema='route_optimizer')
    op.create_index('ux_optimization_run_idempotency', 'optimization_runs', ['tenant_id', 'idempotency_key'], unique=True, schema='route_optimizer', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('aggregate_version > 0', name=op.f('ck_outbox_events_outbox_aggregate_version')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_outbox_attempt_count')),
    sa.CheckConstraint('event_version > 0', name=op.f('ck_outbox_events_outbox_event_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    schema='route_optimizer'
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['tenant_id', 'aggregate_type', 'aggregate_id', 'aggregate_version'], unique=False, schema='route_optimizer')
    op.create_index('ix_outbox_pending', 'outbox_events', ['next_attempt_at', 'occurred_at'], unique=False, schema='route_optimizer', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.create_table('optimization_metrics',
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=False),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('metric_value >= 0', name=op.f('ck_optimization_metrics_optimization_metric_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'optimization_run_id'], ['route_optimizer.optimization_runs.tenant_id', 'route_optimizer.optimization_runs.id'], name='fk_optimization_metrics_tenant_run', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_metrics')),
    sa.UniqueConstraint('tenant_id', 'optimization_run_id', 'metric_name', 'method_type', 'method_name', name='ux_optimization_metric_method'),
    schema='route_optimizer'
    )
    op.create_index('ix_optimization_metric_comparison', 'optimization_metrics', ['tenant_id', 'metric_name', 'method_type', 'method_name', 'created_at'], unique=False, schema='route_optimizer')
    op.create_table('optimization_results',
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('stop_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('legs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_distance_m', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('baseline_type', sa.String(length=100), nullable=False),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('improvement_ratio', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('feasibility_status', sa.String(length=30), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("feasibility_status IN ('FEASIBLE', 'INFEASIBLE', 'PARTIAL', 'FALLBACK')", name=op.f('ck_optimization_results_result_feasibility_status')),
    sa.CheckConstraint('total_cost IS NULL OR total_cost >= 0', name=op.f('ck_optimization_results_result_cost_nonnegative')),
    sa.CheckConstraint('total_distance_m >= 0', name=op.f('ck_optimization_results_result_distance_nonnegative')),
    sa.CheckConstraint('total_duration_seconds >= 0', name=op.f('ck_optimization_results_result_duration_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'optimization_run_id'], ['route_optimizer.optimization_runs.tenant_id', 'route_optimizer.optimization_runs.id'], name='fk_optimization_results_tenant_run', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_results')),
    sa.UniqueConstraint('tenant_id', 'optimization_run_id', name='ux_optimization_result_run'),
    schema='route_optimizer'
    )
    op.create_index('ix_optimization_result_input_hash', 'optimization_results', ['tenant_id', 'input_hash'], unique=False, schema='route_optimizer')
    op.create_table('optimization_stops',
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('trip_stop_id', sa.UUID(), nullable=False),
    sa.Column('input_sequence', sa.Integer(), nullable=False),
    sa.Column('optimized_sequence', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('demand_weight', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('demand_volume', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('service_duration_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('time_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_from_previous_m', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('demand_volume >= 0', name=op.f('ck_optimization_stops_stop_volume_nonnegative')),
    sa.CheckConstraint('demand_weight >= 0', name=op.f('ck_optimization_stops_stop_weight_nonnegative')),
    sa.CheckConstraint('distance_from_previous_m IS NULL OR distance_from_previous_m >= 0', name=op.f('ck_optimization_stops_stop_distance_nonnegative')),
    sa.CheckConstraint('input_sequence > 0', name=op.f('ck_optimization_stops_input_sequence_positive')),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_optimization_stops_stop_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_optimization_stops_stop_longitude_range')),
    sa.CheckConstraint('optimized_sequence IS NULL OR optimized_sequence > 0', name=op.f('ck_optimization_stops_optimized_sequence_positive')),
    sa.CheckConstraint('service_duration_seconds >= 0', name=op.f('ck_optimization_stops_stop_service_duration_nonnegative')),
    sa.CheckConstraint('time_window_end IS NULL OR time_window_start IS NULL OR time_window_end >= time_window_start', name=op.f('ck_optimization_stops_stop_time_window_order')),
    sa.ForeignKeyConstraint(['tenant_id', 'optimization_run_id'], ['route_optimizer.optimization_runs.tenant_id', 'route_optimizer.optimization_runs.id'], name='fk_optimization_stops_tenant_run', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_stops')),
    sa.UniqueConstraint('tenant_id', 'optimization_run_id', 'trip_stop_id', name='ux_optimization_stop'),
    schema='route_optimizer'
    )
    op.create_index('ix_optimization_stop_input_order', 'optimization_stops', ['tenant_id', 'optimization_run_id', 'input_sequence'], unique=False, schema='route_optimizer')
    op.create_index('ux_optimization_stop_sequence', 'optimization_stops', ['tenant_id', 'optimization_run_id', 'optimized_sequence'], unique=True, schema='route_optimizer', postgresql_where=sa.text('optimized_sequence IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_optimization_stop_sequence', table_name='optimization_stops', schema='route_optimizer', postgresql_where=sa.text('optimized_sequence IS NOT NULL'))
    op.drop_index('ix_optimization_stop_input_order', table_name='optimization_stops', schema='route_optimizer')
    op.drop_table('optimization_stops', schema='route_optimizer')
    op.drop_index('ix_optimization_result_input_hash', table_name='optimization_results', schema='route_optimizer')
    op.drop_table('optimization_results', schema='route_optimizer')
    op.drop_index('ix_optimization_metric_comparison', table_name='optimization_metrics', schema='route_optimizer')
    op.drop_table('optimization_metrics', schema='route_optimizer')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', schema='route_optimizer', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events', schema='route_optimizer')
    op.drop_table('outbox_events', schema='route_optimizer')
    op.drop_index('ux_optimization_run_idempotency', table_name='optimization_runs', schema='route_optimizer', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_optimization_run_trip', table_name='optimization_runs', schema='route_optimizer')
    op.drop_index('ix_optimization_run_status_age', table_name='optimization_runs', schema='route_optimizer', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING') AND deleted_at IS NULL"))
    op.drop_index('ix_optimization_run_correlation', table_name='optimization_runs', schema='route_optimizer')
    op.drop_table('optimization_runs', schema='route_optimizer')
    op.execute(sa.text('DROP SCHEMA IF EXISTS "route_optimizer"'))
    # ### end Alembic commands ###
