"""initial forecast schema

Revision ID: 20260905_0001
Revises: 
Create Date: 2026-09-05 21:42:21.658765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260905_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "forecast"'))
    op.create_table('demand_observations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('demand_date', sa.Date(), nullable=False),
    sa.Column('fulfilled_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('source_order_id', sa.UUID(), nullable=False),
    sa.Column('source_version', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('fulfilled_quantity >= 0', name=op.f('ck_demand_observations_fulfilled_quantity_nonnegative')),
    sa.CheckConstraint('source_version > 0', name=op.f('ck_demand_observations_source_version_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_observations')),
    sa.UniqueConstraint('tenant_id', 'source_event_id', 'product_id', name='ux_demand_observation_event_product'),
    sa.UniqueConstraint('tenant_id', 'source_order_id', 'product_id', 'source_version', name='ux_demand_observation_order_product_version'),
    schema='forecast'
    )
    op.create_index('ix_demand_observation_series_date', 'demand_observations', ['tenant_id', 'warehouse_id', 'product_id', 'demand_date'], unique=False, schema='forecast')
    op.create_table('forecast_runs',
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('training_start_date', sa.Date(), nullable=False),
    sa.Column('training_end_date', sa.Date(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('baseline_name', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_sanitized', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED')", name=op.f('ck_forecast_runs_forecast_run_status')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name=op.f('ck_forecast_runs_forecast_execution_time_order')),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_forecast_runs_forecast_horizon_positive')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_forecast_runs_forecast_latency')),
    sa.CheckConstraint('random_seed >= 0', name=op.f('ck_forecast_runs_forecast_random_seed_nonnegative')),
    sa.CheckConstraint('training_end_date >= training_start_date', name=op.f('ck_forecast_runs_forecast_training_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_runs')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_forecast_runs_tenant_id'),
    schema='forecast'
    )
    op.create_index('ix_forecast_run_correlation', 'forecast_runs', ['tenant_id', 'correlation_id'], unique=False, schema='forecast')
    op.create_index('ix_forecast_run_status_age', 'forecast_runs', ['tenant_id', 'status', 'created_at'], unique=False, schema='forecast', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING') AND deleted_at IS NULL"))
    op.create_index('ux_forecast_run_idempotency', 'forecast_runs', ['tenant_id', 'idempotency_key'], unique=True, schema='forecast', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('inbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_events')),
    sa.UniqueConstraint('consumer_name', 'event_id', name='ux_inbox_consumer_event'),
    schema='forecast'
    )
    op.create_index('ix_inbox_aggregate_version', 'inbox_events', ['tenant_id', 'aggregate_id', 'aggregate_version'], unique=False, schema='forecast')
    op.create_index('ix_inbox_tenant_event', 'inbox_events', ['tenant_id', 'event_id'], unique=False, schema='forecast')
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('aggregate_version > 0', name=op.f('ck_outbox_events_outbox_aggregate_version')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_outbox_attempt_count')),
    sa.CheckConstraint('event_version > 0', name=op.f('ck_outbox_events_outbox_event_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    schema='forecast'
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['tenant_id', 'aggregate_type', 'aggregate_id', 'aggregate_version'], unique=False, schema='forecast')
    op.create_index('ix_outbox_pending', 'outbox_events', ['next_attempt_at', 'occurred_at'], unique=False, schema='forecast', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.create_table('forecast_series',
    sa.Column('forecast_run_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('fallback_reason', sa.String(length=200), nullable=True),
    sa.Column('model_artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('model_artifact_checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED', 'INSUFFICIENT_DATA')", name=op.f('ck_forecast_series_forecast_series_status')),
    sa.CheckConstraint('confidence_level > 0 AND confidence_level < 1', name=op.f('ck_forecast_series_forecast_series_confidence_range')),
    sa.CheckConstraint('observation_count >= 0', name=op.f('ck_forecast_series_observation_count_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'forecast_run_id'], ['forecast.forecast_runs.tenant_id', 'forecast.forecast_runs.id'], name='fk_forecast_series_tenant_run', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_series')),
    sa.UniqueConstraint('tenant_id', 'forecast_run_id', 'warehouse_id', 'product_id', name='ux_forecast_series_run_scope'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_forecast_series_tenant_id'),
    schema='forecast'
    )
    op.create_index('ix_forecast_series_lookup', 'forecast_series', ['tenant_id', 'warehouse_id', 'product_id', 'created_at'], unique=False, schema='forecast')
    op.create_table('forecast_metrics',
    sa.Column('forecast_series_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=20), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('method_type', sa.String(length=20), nullable=False),
    sa.Column('method_name', sa.String(length=100), nullable=False),
    sa.Column('evaluation_start_date', sa.Date(), nullable=False),
    sa.Column('evaluation_end_date', sa.Date(), nullable=False),
    sa.Column('zero_actual_policy', sa.String(length=50), nullable=False),
    sa.Column('eligible_point_count', sa.Integer(), nullable=False),
    sa.Column('total_point_count', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("method_type IN ('MODEL', 'BASELINE')", name=op.f('ck_forecast_metrics_forecast_method_type')),
    sa.CheckConstraint("metric_name IN ('MAPE', 'RMSE')", name=op.f('ck_forecast_metrics_forecast_metric_name')),
    sa.CheckConstraint('eligible_point_count <= total_point_count', name=op.f('ck_forecast_metrics_eligible_points_within_total')),
    sa.CheckConstraint('eligible_point_count >= 0', name=op.f('ck_forecast_metrics_eligible_points_nonnegative')),
    sa.CheckConstraint('evaluation_end_date >= evaluation_start_date', name=op.f('ck_forecast_metrics_metric_evaluation_range')),
    sa.CheckConstraint('metric_value IS NULL OR metric_value >= 0', name=op.f('ck_forecast_metrics_metric_nonnegative')),
    sa.CheckConstraint('total_point_count >= 0', name=op.f('ck_forecast_metrics_total_points_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'forecast_series_id'], ['forecast.forecast_series.tenant_id', 'forecast.forecast_series.id'], name='fk_forecast_metrics_tenant_series', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_metrics')),
    sa.UniqueConstraint('tenant_id', 'forecast_series_id', 'metric_name', 'method_type', 'method_name', 'evaluation_start_date', 'evaluation_end_date', name='ux_forecast_metric_evaluation'),
    schema='forecast'
    )
    op.create_index('ix_forecast_metric_comparison', 'forecast_metrics', ['tenant_id', 'metric_name', 'method_type', 'method_name', 'calculated_at'], unique=False, schema='forecast')
    op.create_table('forecast_results',
    sa.Column('forecast_series_id', sa.UUID(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('predicted_quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('lower_bound', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('upper_bound', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('baseline_naive', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('baseline_moving_average_7', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('actual_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_quantity IS NULL OR actual_quantity >= 0', name=op.f('ck_forecast_results_actual_quantity_nonnegative')),
    sa.CheckConstraint('baseline_moving_average_7 IS NULL OR baseline_moving_average_7 >= 0', name=op.f('ck_forecast_results_baseline_moving_average_nonnegative')),
    sa.CheckConstraint('baseline_naive IS NULL OR baseline_naive >= 0', name=op.f('ck_forecast_results_baseline_naive_nonnegative')),
    sa.CheckConstraint('confidence_level > 0 AND confidence_level < 1', name=op.f('ck_forecast_results_forecast_result_confidence_range')),
    sa.CheckConstraint('lower_bound IS NULL OR lower_bound >= 0', name=op.f('ck_forecast_results_lower_bound_nonnegative')),
    sa.CheckConstraint('lower_bound IS NULL OR upper_bound IS NULL OR upper_bound >= lower_bound', name=op.f('ck_forecast_results_forecast_bounds_order')),
    sa.CheckConstraint('predicted_quantity >= 0', name=op.f('ck_forecast_results_predicted_quantity_nonnegative')),
    sa.CheckConstraint('upper_bound IS NULL OR upper_bound >= 0', name=op.f('ck_forecast_results_upper_bound_nonnegative')),
    sa.ForeignKeyConstraint(['tenant_id', 'forecast_series_id'], ['forecast.forecast_series.tenant_id', 'forecast.forecast_series.id'], name='fk_forecast_results_tenant_series', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecast_results')),
    sa.UniqueConstraint('tenant_id', 'forecast_series_id', 'forecast_date', name='ux_forecast_result_series_date'),
    schema='forecast'
    )
    op.create_index('ix_forecast_result_date', 'forecast_results', ['tenant_id', 'forecast_date'], unique=False, schema='forecast')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_result_date', table_name='forecast_results', schema='forecast')
    op.drop_table('forecast_results', schema='forecast')
    op.drop_index('ix_forecast_metric_comparison', table_name='forecast_metrics', schema='forecast')
    op.drop_table('forecast_metrics', schema='forecast')
    op.drop_index('ix_forecast_series_lookup', table_name='forecast_series', schema='forecast')
    op.drop_table('forecast_series', schema='forecast')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', schema='forecast', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events', schema='forecast')
    op.drop_table('outbox_events', schema='forecast')
    op.drop_index('ix_inbox_tenant_event', table_name='inbox_events', schema='forecast')
    op.drop_index('ix_inbox_aggregate_version', table_name='inbox_events', schema='forecast')
    op.drop_table('inbox_events', schema='forecast')
    op.drop_index('ux_forecast_run_idempotency', table_name='forecast_runs', schema='forecast', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_forecast_run_status_age', table_name='forecast_runs', schema='forecast', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING') AND deleted_at IS NULL"))
    op.drop_index('ix_forecast_run_correlation', table_name='forecast_runs', schema='forecast')
    op.drop_table('forecast_runs', schema='forecast')
    op.drop_index('ix_demand_observation_series_date', table_name='demand_observations', schema='forecast')
    op.drop_table('demand_observations', schema='forecast')
    op.execute(sa.text('DROP SCHEMA IF EXISTS "forecast"'))
    # ### end Alembic commands ###
