import type { ServiceId } from '@logix/common';

/**
 * DomainEventEnvelope — The standardized event wrapper for all Kafka messages.
 *
 * Every domain event published to Kafka must be wrapped in this envelope.
 * This contract directly implements the specification from:
 * @see docs/architecture/event-architecture.md §2 (Minimal event envelope)
 *
 * Field semantics:
 * - eventId: unique identifier for this specific event occurrence
 * - eventType: discriminator (e.g., 'OrderConfirmed', 'InventoryReserved')
 * - eventVersion: schema version for backward-compatible evolution (§11)
 * - occurredAt: ISO 8601 timestamp of the business fact
 * - producer: the service that owns the state change (§4)
 * - tenantId: mandatory for tenant isolation (architecture principle #4)
 * - actorId: the user who triggered the action (§10)
 * - correlationId: traces the entire request chain (§10)
 * - causationId: the direct parent operation that caused this event (§10)
 * - aggregateType: the domain aggregate that changed
 * - aggregateId: instance identifier of the aggregate
 * - aggregateVersion: monotonic version for ordering/deduplication (§6)
 * - payload: the event-specific data
 */
export interface DomainEventEnvelope<TPayload = unknown> {
  readonly eventId: string;
  readonly eventType: string;
  readonly eventVersion: number;
  readonly occurredAt: string;
  readonly producer: ServiceId;
  readonly tenantId: string;
  readonly actorId: string;
  readonly correlationId: string;
  readonly causationId: string;
  readonly aggregateType: string;
  readonly aggregateId: string;
  readonly aggregateVersion: number;
  readonly payload: TPayload;
}

/**
 * Parameters for creating a new domain event.
 * eventId and occurredAt are auto-generated by the producer service.
 */
export type CreateDomainEvent<TPayload = unknown> = Omit<
  DomainEventEnvelope<TPayload>,
  'eventId' | 'occurredAt'
>;
