"""initial agent schema

Revision ID: 20260905_0001
Revises: 
Create Date: 2026-09-05 21:42:21.671211
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260905_0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE SCHEMA IF NOT EXISTS "agent"'))
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_conversations_tenant_id'),
    schema='agent'
    )
    op.create_index('ix_conversations_user_recent', 'conversations', ['tenant_id', 'user_id', sa.literal_column('last_message_at DESC')], unique=False, schema='agent', postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL"))
    op.create_table('inbox_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=True),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbox_events')),
    sa.UniqueConstraint('consumer_name', 'event_id', name='ux_inbox_consumer_event'),
    schema='agent'
    )
    op.create_index('ix_inbox_aggregate_version', 'inbox_events', ['tenant_id', 'aggregate_id', 'aggregate_version'], unique=False, schema='agent')
    op.create_index('ix_inbox_tenant_event', 'inbox_events', ['tenant_id', 'event_id'], unique=False, schema='agent')
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('endpoint_alias', sa.String(length=100), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('credential_ref', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_provider_configs')),
    schema='agent'
    )
    op.create_index('ux_active_platform_provider_config', 'llm_provider_configs', ['provider'], unique=True, schema='agent', postgresql_where=sa.text('tenant_id IS NULL AND is_active = true AND deleted_at IS NULL'))
    op.create_index('ux_active_tenant_provider_config', 'llm_provider_configs', ['tenant_id', 'provider'], unique=True, schema='agent', postgresql_where=sa.text('tenant_id IS NOT NULL AND is_active = true AND deleted_at IS NULL'))
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('aggregate_version', sa.BigInteger(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('aggregate_version > 0', name=op.f('ck_outbox_events_outbox_aggregate_version')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_outbox_events_outbox_attempt_count')),
    sa.CheckConstraint('event_version > 0', name=op.f('ck_outbox_events_outbox_event_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    schema='agent'
    )
    op.create_index('ix_outbox_aggregate', 'outbox_events', ['tenant_id', 'aggregate_type', 'aggregate_id', 'aggregate_version'], unique=False, schema='agent')
    op.create_index('ix_outbox_pending', 'outbox_events', ['next_attempt_at', 'occurred_at'], unique=False, schema='agent', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.create_table('agent_executions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('thread_id', sa.String(length=200), nullable=False),
    sa.Column('agent_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'QUEUED'"), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_policy_version', sa.String(length=100), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message_sanitized', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('QUEUED', 'RUNNING', 'WAITING_TOOL', 'WAITING_CONFIRMATION', 'SUCCEEDED', 'FAILED', 'CANCELED', 'TIMED_OUT')", name=op.f('ck_agent_executions_agent_execution_status')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_agent_executions_execution_latency')),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['agent.conversations.tenant_id', 'agent.conversations.id'], name='fk_executions_tenant_conversation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_executions')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_agent_executions_tenant_id'),
    schema='agent'
    )
    op.create_index('ix_agent_execution_correlation', 'agent_executions', ['tenant_id', 'correlation_id'], unique=False, schema='agent')
    op.create_index('ix_agent_execution_metrics', 'agent_executions', ['tenant_id', 'provider', 'model', sa.literal_column('finished_at DESC')], unique=False, schema='agent', postgresql_where=sa.text('finished_at IS NOT NULL'))
    op.create_index('ix_agent_execution_status_age', 'agent_executions', ['tenant_id', 'status', 'created_at'], unique=False, schema='agent', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING', 'WAITING_TOOL', 'WAITING_CONFIRMATION') AND deleted_at IS NULL"))
    op.create_index('ix_agent_execution_user_recent', 'agent_executions', ['tenant_id', 'user_id', sa.literal_column('created_at DESC')], unique=False, schema='agent')
    op.create_index('ux_agent_execution_idempotency', 'agent_executions', ['tenant_id', 'user_id', 'idempotency_key'], unique=True, schema='agent', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_redacted', sa.Text(), nullable=False),
    sa.Column('model_message_id', sa.String(length=200), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('SYSTEM', 'USER', 'ASSISTANT', 'TOOL')", name=op.f('ck_conversation_messages_message_role')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_conversation_messages_message_sequence_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'conversation_id'], ['agent.conversations.tenant_id', 'agent.conversations.id'], name='fk_messages_tenant_conversation', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('tenant_id', 'conversation_id', 'sequence', name='ux_message_sequence'),
    schema='agent'
    )
    op.create_index('ix_message_timeline', 'conversation_messages', ['tenant_id', 'conversation_id', 'created_at', 'id'], unique=False, schema='agent')
    op.create_table('agent_model_calls',
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('model_profile', sa.String(length=100), nullable=False),
    sa.Column('gateway_backend', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_policy_version', sa.String(length=100), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('fallback_from_call_id', sa.UUID(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('provider_request_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count > 0', name=op.f('ck_agent_model_calls_model_call_attempt_positive')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_agent_model_calls_input_tokens')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_agent_model_calls_model_latency')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_agent_model_calls_output_tokens')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_agent_model_calls_model_call_sequence_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'fallback_from_call_id'], ['agent.agent_model_calls.tenant_id', 'agent.agent_model_calls.id'], name='fk_model_calls_fallback', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_execution_id'], ['agent.agent_executions.tenant_id', 'agent.agent_executions.id'], name='fk_model_calls_tenant_execution', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_model_calls')),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_agent_model_calls_tenant_id'),
    sa.UniqueConstraint('tenant_id', 'agent_execution_id', 'sequence', name='ux_model_call_sequence'),
    schema='agent'
    )
    op.create_index('ix_model_call_metrics', 'agent_model_calls', ['tenant_id', 'provider', 'model', 'status', sa.literal_column('created_at DESC')], unique=False, schema='agent')
    op.create_table('tool_calls',
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('tool_version', sa.String(length=50), nullable=False),
    sa.Column('required_permission', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('input_sanitized', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('output_sanitized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('target_service', sa.String(length=100), nullable=True),
    sa.Column('business_entity_type', sa.String(length=100), nullable=True),
    sa.Column('business_entity_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count > 0', name=op.f('ck_tool_calls_tool_attempt_positive')),
    sa.CheckConstraint('latency_ms IS NULL OR latency_ms >= 0', name=op.f('ck_tool_calls_tool_latency')),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_tool_calls_tool_call_sequence_positive')),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_execution_id'], ['agent.agent_executions.tenant_id', 'agent.agent_executions.id'], name='fk_tool_calls_tenant_execution', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_calls')),
    sa.UniqueConstraint('tenant_id', 'agent_execution_id', 'sequence', name='ux_tool_call_sequence'),
    sa.UniqueConstraint('tenant_id', 'id', name='uq_tool_calls_tenant_id'),
    schema='agent'
    )
    op.create_index('ix_tool_call_business_entity', 'tool_calls', ['tenant_id', 'business_entity_type', 'business_entity_id'], unique=False, schema='agent')
    op.create_index('ix_tool_call_metrics', 'tool_calls', ['tenant_id', 'tool_name', 'status', sa.literal_column('finished_at DESC')], unique=False, schema='agent')
    op.create_index('ux_tool_call_idempotency', 'tool_calls', ['tenant_id', 'agent_execution_id', 'idempotency_key'], unique=True, schema='agent', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.create_table('confirmation_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_execution_id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('expected_target_version', sa.BigInteger(), nullable=False),
    sa.Column('preview_payload_sanitized', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'EXPIRED', 'CONSUMED')", name=op.f('ck_confirmation_requests_confirmation_status')),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_execution_id'], ['agent.agent_executions.tenant_id', 'agent.agent_executions.id'], name='fk_confirmations_tenant_execution', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id', 'tool_call_id'], ['agent.tool_calls.tenant_id', 'agent.tool_calls.id'], name='fk_confirmations_tenant_tool_call', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmation_requests')),
    schema='agent'
    )
    op.create_index('ix_confirmation_user_pending', 'confirmation_requests', ['tenant_id', 'user_id', 'expires_at'], unique=False, schema='agent', postgresql_where=sa.text("status = 'PENDING' AND deleted_at IS NULL"))
    op.create_index('ux_confirmation_context_consumed', 'confirmation_requests', ['tenant_id', 'user_id', 'context_hash'], unique=True, schema='agent', postgresql_where=sa.text("status = 'CONSUMED'"))
    op.create_index('ux_pending_tool_confirmation', 'confirmation_requests', ['tenant_id', 'tool_call_id'], unique=True, schema='agent', postgresql_where=sa.text("status = 'PENDING' AND deleted_at IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_pending_tool_confirmation', table_name='confirmation_requests', schema='agent', postgresql_where=sa.text("status = 'PENDING' AND deleted_at IS NULL"))
    op.drop_index('ux_confirmation_context_consumed', table_name='confirmation_requests', schema='agent', postgresql_where=sa.text("status = 'CONSUMED'"))
    op.drop_index('ix_confirmation_user_pending', table_name='confirmation_requests', schema='agent', postgresql_where=sa.text("status = 'PENDING' AND deleted_at IS NULL"))
    op.drop_table('confirmation_requests', schema='agent')
    op.drop_index('ux_tool_call_idempotency', table_name='tool_calls', schema='agent', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_tool_call_metrics', table_name='tool_calls', schema='agent')
    op.drop_index('ix_tool_call_business_entity', table_name='tool_calls', schema='agent')
    op.drop_table('tool_calls', schema='agent')
    op.drop_index('ix_model_call_metrics', table_name='agent_model_calls', schema='agent')
    op.drop_table('agent_model_calls', schema='agent')
    op.drop_index('ix_message_timeline', table_name='conversation_messages', schema='agent')
    op.drop_table('conversation_messages', schema='agent')
    op.drop_index('ux_agent_execution_idempotency', table_name='agent_executions', schema='agent', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_index('ix_agent_execution_user_recent', table_name='agent_executions', schema='agent')
    op.drop_index('ix_agent_execution_status_age', table_name='agent_executions', schema='agent', postgresql_where=sa.text("status IN ('QUEUED', 'RUNNING', 'WAITING_TOOL', 'WAITING_CONFIRMATION') AND deleted_at IS NULL"))
    op.drop_index('ix_agent_execution_metrics', table_name='agent_executions', schema='agent', postgresql_where=sa.text('finished_at IS NOT NULL'))
    op.drop_index('ix_agent_execution_correlation', table_name='agent_executions', schema='agent')
    op.drop_table('agent_executions', schema='agent')
    op.drop_index('ix_outbox_pending', table_name='outbox_events', schema='agent', postgresql_where=sa.text('published_at IS NULL AND deleted_at IS NULL'))
    op.drop_index('ix_outbox_aggregate', table_name='outbox_events', schema='agent')
    op.drop_table('outbox_events', schema='agent')
    op.drop_index('ux_active_tenant_provider_config', table_name='llm_provider_configs', schema='agent', postgresql_where=sa.text('tenant_id IS NOT NULL AND is_active = true AND deleted_at IS NULL'))
    op.drop_index('ux_active_platform_provider_config', table_name='llm_provider_configs', schema='agent', postgresql_where=sa.text('tenant_id IS NULL AND is_active = true AND deleted_at IS NULL'))
    op.drop_table('llm_provider_configs', schema='agent')
    op.drop_index('ix_inbox_tenant_event', table_name='inbox_events', schema='agent')
    op.drop_index('ix_inbox_aggregate_version', table_name='inbox_events', schema='agent')
    op.drop_table('inbox_events', schema='agent')
    op.drop_index('ix_conversations_user_recent', table_name='conversations', schema='agent', postgresql_where=sa.text("status = 'ACTIVE' AND deleted_at IS NULL"))
    op.drop_table('conversations', schema='agent')
    op.execute(sa.text('DROP SCHEMA IF EXISTS "agent"'))
    # ### end Alembic commands ###
